### PR TITLE
Change shell for hdd-chroot.sh to bash

### PR DESCRIPTION
**Pull request by Jonathan50**
because many distros don't use bash as `sh`

### CODE REVIEW

**Comment by TheMatrixShibe** [comment]
/bin/sh always points to the correct shell and is protected by POSIX. I see your point but not everyone uses bash, too.

**Comment by Jonathan50** [comment]
Ok.
Are you sure `hdd-chroot.sh` is POSIX compliant? Because I get
```
./hdd-chroot.sh: 2: [: -ne: unexpected operator
```

**Comment by TheMatrixShibe** [comment]
Seems right. [This](http://www.tldp.org/LDP/abs/html/comparison-ops.html) reads -ne translates to not equal to, but I'll look into it. Thanks.

**Comment by Jonathan50** [comment]
I think that may be a bash extension.

**Comment by TheMatrixShibe** [comment]
I changed that to != based on what information I could find and I think it should work.

**Pull request closed without merging**
